name: echo test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: read-repo-name
        run: |
          DIR_NAMEA=${GITHUB_REPOSITORY##*/}
          echo "DIR_NAMEA=$DIR_NAMEA" >> $GITHUB_ENV
          DIR_NAMEB="${{ env.DIR_NAMEA }}"
          echo $DIR_NAMEB
