name: Test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  l3build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install ghostscript
    - name: Install TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package_file: .github/tl_packages
      # update-all-packages: true
    - name: Install Google Fonts
      run: |
          wget -O chiron-sung-hk-1.017.zip https://github.com/chiron-fonts/chiron-sung-hk/archive/refs/tags/v1.017.zip
          unzip -d chiron-sung-hk-1.017/ chiron-sung-hk-1.017.zip
          mv chiron-sung-hk-1.017/otf/ /usr/share/fonts/
          fc-cache -fv
    - name: Build CTAN release zip with l3build
      run: l3build ctan