name: Test

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  l3build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install ghostscript
    - name: Install TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        package_file: .github/tl_packages
      # update-all-packages: true
    - name: Install HK Fonts
      run: |
          wget -O chiron-sung-hk-1.017.zip https://github.com/chiron-fonts/chiron-sung-hk/blob/release/OTF/ChironSungHK-R.otf
          mv ChironSungHK-R.otf /usr/share/fonts/
          wget -O chiron-sung-hk-1.017.zip https://github.com/chiron-fonts/chiron-sung-hk/blob/release/OTF/ChironSungHK-B.otf
          mv ChironSungHK-B.otf /usr/share/fonts/
          fc-cache -fv
    - name: Build CTAN release zip with l3build
      run: l3build ctan