name: Automated testing

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  l3build:
    runs-on: macos-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install TeX Live
      run: |
        brew install mactex-no-gui
        sudo ln -s /usr/local/texlive/2025/bin/universal-darwin/tlmgr /usr/local/bin/tlmgr
        sudo tlmgr path add

    - name: Install l3build
      run: sudo tlmgr install l3build

    - name: Build CTAN release zip with l3build
      run: l3build ctan
